pull_request_rules:
  - name: merge Scala Steward's PRs
    conditions:
      - base=master
      - author=scala-steward
      - "status-success=ci/circleci: lint"
      - "status-success=ci/circleci: check_docs"
      - "status-success=ci/circleci: test213_jdk17"
      - "status-success=ci/circleci: test213_jdk23"
      - "status-success=ci/circleci: test_dotty_jdk17"
    actions:
      merge:
        method: squash
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
