version: 2.1
parameters:
  tag_regex:
    type: string
    default: /^v\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/
jobs:
  lint:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-17.0.19_10_2.x
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-3
      - run: sbt "++2.13.18!; check"
      - save_cache:
          key: sbt-cache-3
          paths:
            - "~/.cache/coursier/"
            - "~/.sbt"
            - "~/.m2"
  check_docs:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-17.0.19_10_2.x
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-3
      - run: sbt "++2.13.18!; docs/paradox"

  test213_jdk17:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-17.0.19_10_2.x

    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-3
      - run: sbt "++2.13.18!; compile; rezilienceJVM/test; config/test"
      - save_cache:
          key: sbt-cache-3
          paths:
            - "~/.cache/coursier/"
            - "~/.sbt"
            - "~/.m2"
  test213_jdk25:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-25.0.3_9_2.x
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-3
      - run: sbt "++2.13.18!; compile; rezilienceJVM/test"
      - save_cache:
          key: sbt-cache-3
          paths:
            - "~/.cache/coursier/"
            - "~/.sbt"
            - "~/.m2"
  test_dotty_jdk17:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-17.0.19_10_2.x
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-3
      - run: sbt "++3.3.8!; rezilienceJVM/test"
      - save_cache:
          key: sbt-cache-3
          paths:
            - "~/.cache/coursier/"
            - "~/.sbt"
            - "~/.m2"
  release:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-17.0.19_10_2.x
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-3
      - run: apt update
      - run: apt install -y gnupg
      - run: export GPG_TTY=$(tty)
      - run: echo $PGP_SECRET | base64 --decode | gpg --batch --import
      - run: sbt ci-release

  publish_docs:
    docker:
      - image: sbtscala/scala-sbt:eclipse-temurin-17.0.19_10_2.x
    steps:
      - checkout
      - run: sbt "++2.13.18!; publishLocal; docs/makeSite; ghpagesPushSite"

workflows:
  version: 2
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - check_docs:
          requires:
            - lint
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - test213_jdk17:
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - test213_jdk25:
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - test_dotty_jdk17:
          filters:
            tags:
              only: << pipeline.parameters.tag_regex >>
      - release:
          requires:
            - test213_jdk17
            - test213_jdk25
            - test_dotty_jdk17
            - check_docs
          filters:
            branches:
              only:
                - master
            tags:
              only: << pipeline.parameters.tag_regex >>
      - publish_docs:
          requires:
             - release
          filters:
            branches:
              only:
                - master
