addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.5.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.4.2")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"             % "2.1.1")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.13.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("io.shiftleft"              % "sbt-ci-release-early"     % "2.0.39")
addSbtPlugin("com.47deg"                 % "sbt-microsites"           % "1.4.2")
addSbtPlugin("com.github.sbt"            % "sbt-unidoc"               % "0.5.0")

addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.11")
addSbtPlugin("com.github.sbt" % "sbt-pgp"        % "2.2.1")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"     % "4.1.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"   % "3.9.17")
