addSbtPlugin("org.scalameta"             % "sbt-scalafmt"             % "2.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"             % "0.1.16")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"             % "0.15.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"              % "1.5.0")
addSbtPlugin("org.portable-scala"        % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("io.shiftleft"              % "sbt-ci-release-early"     % "2.0.16")
addSbtPlugin("com.47deg"                 % "sbt-microsites"           % "1.3.2")
addSbtPlugin("com.eed3si9n"              % "sbt-unidoc"               % "0.4.3")

addSbtPlugin("com.geirsson"   % "sbt-ci-release" % "1.5.5")
addSbtPlugin("com.github.sbt" % "sbt-pgp"        % "2.1.2")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"     % "4.1.1")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"   % "3.9.6")
